"""rename department

Revision ID: 314f43a25f46
Revises: 5a458ba3a1aa
Create Date: 2024-04-02 16:02:33.433690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314f43a25f46'
down_revision = '5a458ba3a1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
